import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from 'next/head'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "godwin.porforlio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Godwin — Fullstack Web Developer (React & Next.js)</title>
        <meta name="description" content="ZenCode — silent coding with modern React & Next.js projects. Hire me for landing pages, SaaS UIs and animations." />
        <meta property="og:title" content="Godwin - React & Next.js developer" />
        <meta property="og:image" content="/og-image.png" />
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
